### ISSUE TITLE
Feedback page.

### ISSUE THREAD

**Issue by Jeancoicou** [m1gh/angrynerds#6]
The feedback page currently does not save forms to the database to display on the page.

**Comment by CameronSchultzUSF** [comment]
Is the form not working or is the issue with the feedback on the page. Note that the feedback on the page was never intended to be live data from the database. Just hand selected reputable feedback as you often see on many sites

**Comment by Jeancoicou** [comment]
Ah, ok. Also just realized I didn't refresh the tables after submitting feedback. So it's working fine. Closing this issue.
